type: object
required:
  - id
  - name
  - description
properties:
  id:
    type: string
    format: uuid
    description: Unique identifier for the training program.
  name:
    type: string
    description: Name of the training program.
  description:
    type: string
    description: Description of the training program.
