type: object
required:
  - id
  - profileId
  - name
  - description
properties:
  id:
    type: string
    format: uuid
    description: Unique identifier for the training program.
  profileId:
    type: string
    format: uuid
    description: Unique identifier for the profile.
  name:
    type: string
    description: Name of the training program.
  description:
    type: string
    description: Description of the training program.
  createdAt:
    type: string
    format: date-time
    description: Timestamp when the training program created.
  updatedAt:
    type: string
    format: date-time
    description: Timestamp when the training program updated.
